const $=id=>document.getElementById(id);let contract,state;
const labels={submit_plan:'Представить план',approve_plan:'Утвердить план',reject_plan:'Отклонить план',submit_result:'Передать реализацию',fail_validation:'Проверка не пройдена',approve_validation:'Утвердить валидацию'};
const defaults={submit_plan:'План: определить формат, реализовать экспорт, добавить тесты',approve_plan:'План проверен и утверждён',reject_plan:'Нужно добавить критерии готовности',submit_result:'Экспорт PDF реализован, тесты добавлены',fail_validation:'PDF повреждён — требуется исправление',approve_validation:'PDF открыт, содержимое и тесты проверены'};
async function json(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
function post(url,body){return json(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}
function escapeText(value){const node=document.createElement('span');node.textContent=value;return node.innerHTML;}
function renderTimeline(){const current=state?.state;const states=contract.states;const index=states.findIndex(item=>item.id===current);$('timeline').replaceChildren(...states.map((item,i)=>{const node=document.createElement('article');node.className=`step ${item.id===current?'current':i<index?'past':''}`;node.innerHTML='<b></b><small></small>';node.querySelector('b').textContent=item.title;node.querySelector('small').textContent=item.id;return node;}));}
function render(response){state=response.state;$('state-name').textContent=`${contract.states.find(x=>x.id===state.state)?.title||state.state}${state.paused?' · ПАУЗА':''}`;$('state-meta').textContent=`${state.state} · версия ${state.version}`;$('message').textContent=response.message;$('actions').replaceChildren(...response.allowed_actions.map(action=>{const button=document.createElement('button');button.dataset.action=action;button.textContent=labels[action]||action;button.addEventListener('click',()=>transition(action));return button;}));const entries=Object.entries(state.artifacts);$('artifacts').innerHTML=entries.length?entries.map(([key,value])=>`<article><b>${escapeText(key)}</b><p>${escapeText(value)}</p></article>`).join(''):'<p class="muted">Пока пусто.</p>';$('history').innerHTML=response.history.slice().reverse().map(item=>`<article class="event ${item.allowed?'ok':'rejected'}"><b>${item.allowed?'✓':'×'} ${escapeText(item.event)}</b><span>${escapeText(item.from_state||'—')} → ${escapeText(item.to_state||'—')}</span><small>${escapeText(item.action||item.code)} · ${escapeText(item.details)}</small></article>`).join('');renderTimeline();$('status').textContent=response.allowed===false?`Переход заблокирован: ${response.message}`:'Состояние сохранено. Модель не имеет доступа к записи.';}
async function create(){render(await post('/api/task',{task_id:$('task-id').value,objective:$('objective').value}));}
async function loadTask(){render(await json(`/api/task?task_id=${encodeURIComponent($('task-id').value)}`));}
async function transition(action){const result=defaults[action]||$('result').value;$('result').value=result;render(await post('/api/transition',{task_id:state.task_id,action,result,expected_version:state.version}));}
async function compare(){if(!state)throw new Error('Сначала создайте задачу');$('status').textContent='Обе модели анализируют один снимок…';const before=state.version;const data=await post('/api/compare',{task_id:state.task_id,request:$('model-request').value});$('models').innerHTML=data.results.map(item=>`<article class="model ${item.status}"><div><b>${escapeText(item.label)}</b><small>${escapeText(item.provider)} · ${item.elapsed_ms} мс</small></div><p>${escapeText(item.answer)}</p></article>`).join('');$('status').textContent=`Сравнение завершено. Версия ${before} не изменилась; TransitionGuard не вызывался.`;}
async function pause(){render(await post('/api/pause',{task_id:state.task_id,reason:'Пауза для проверки восстановления'}));}
async function resume(){render(await post('/api/resume',{task_id:state.task_id}));}
async function init(){contract=await json('/api/lifecycle');$('contract-version').textContent=`контракт v${contract.version}`;renderTimeline();}
$('create').addEventListener('click',()=>create().catch(showError));$('load').addEventListener('click',()=>loadTask().catch(showError));$('invalid').addEventListener('click',()=>{if(!state)return showError(new Error('Сначала создайте задачу'));transition('approve_validation').catch(showError);});$('pause').addEventListener('click',()=>pause().catch(showError));$('resume').addEventListener('click',()=>resume().catch(showError));$('compare').addEventListener('click',()=>compare().catch(showError));function showError(error){$('status').textContent=`Ошибка: ${error.message}`;}init().catch(showError);
