#!/usr/bin/env node
// Deterministic Day 15 browser demo recorded through Chrome CDP and ffmpeg.
import {spawn,spawnSync} from 'node:child_process';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,realpathSync} from 'node:fs';
import os from 'node:os';import path from 'node:path';import net from 'node:net';import {fileURLToPath} from 'node:url';
const dayDir=path.dirname(fileURLToPath(import.meta.url)),rootDir=path.resolve(dayDir,'..');
const framesDir=mkdtempSync(path.join(os.tmpdir(),'day15-frames-')),chromeDir=mkdtempSync(path.join(os.tmpdir(),'day15-chrome-'));
const output=process.argv.includes('--out')?path.resolve(process.argv[process.argv.indexOf('--out')+1]):path.join(rootDir,'ChallengeVideos','day15-demo.mp4');mkdirSync(path.dirname(output),{recursive:true});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));function freePort(){return new Promise((resolve,reject)=>{const server=net.createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const port=server.address().port;server.close(()=>resolve(port));});});}
const port=await freePort(),cdpPort=await freePort();const chromePath=process.env.CHROME_PATH||path.join(process.env.ProgramFiles||'','Google','Chrome','Application','chrome.exe');
const server=spawn(process.env.PYTHON_PATH||'python',['web_server.py','--port',String(port)],{cwd:dayDir,stdio:'ignore'});const chrome=spawn(chromePath,['--headless=new',`--remote-debugging-port=${cdpPort}`,'--no-sandbox',`--user-data-dir=${chromeDir}`,'--disable-gpu','--window-size=1440,1000','--hide-scrollbars','about:blank'],{stdio:'ignore'});
let socket,recording=true,frame=0,callId=0;const pending=new Map();async function waitJson(url){for(let i=0;i<120;i++){try{const response=await fetch(url);if(response.ok)return response.json();}catch{}await sleep(250);}throw new Error(`Не дождался ${url}`);}function cdp(method,params={}){return new Promise((resolve,reject)=>{const id=++callId;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});}async function evaluate(expression){const result=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.text);return result.result.value;}async function camera(){while(recording){const {data}=await cdp('Page.captureScreenshot',{format:'png',optimizeForSpeed:true});writeFileSync(path.join(framesDir,`f${String(frame++).padStart(5,'0')}.png`),Buffer.from(data,'base64'));await sleep(125);}}
function caption(title,detail){return `(()=>{let box=document.getElementById('video-caption');if(!box){box=document.createElement('div');box.id='video-caption';box.style.cssText='position:fixed;top:0;left:0;right:0;z-index:9999;padding:9px 22px 11px;background:#030a10f5;border-bottom:2px solid #72b7ff;text-align:center;font-family:Segoe UI;color:white';box.innerHTML='<b></b><span></span>';box.querySelector('b').style.cssText='display:block;color:#ffd26a;font-size:21px';box.querySelector('span').style.cssText='display:block;font-size:15px;color:#d7e7f4';document.body.append(box);document.querySelector('main').style.paddingTop='98px'}box.querySelector('b').textContent=${JSON.stringify(title)};box.querySelector('span').textContent=${JSON.stringify(detail)};})()`;}function focus(selector){return `(()=>{document.querySelectorAll('.video-focus').forEach(x=>{x.classList.remove('video-focus');x.style.removeProperty('outline');x.style.removeProperty('box-shadow')});document.querySelectorAll(${JSON.stringify(selector)}).forEach(x=>{x.classList.add('video-focus');x.style.outline='3px solid #ffd26a';x.style.boxShadow='0 0 24px #ffd26a77'})})()`;}async function scene(title,detail,selector,ms=3500){await evaluate(caption(title,detail));await evaluate(focus(selector));await sleep(ms);}async function waitText(id,text,limit=900){for(let i=0;i<limit;i++){if((await evaluate(`document.getElementById(${JSON.stringify(id)}).textContent`)).includes(text))return;const status=await evaluate("document.getElementById('status').textContent");if(status.startsWith('Ошибка:'))throw new Error(status);await sleep(100);}throw new Error(`Не появился текст ${text}`);}async function click(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(500);}async function scroll(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({behavior:'smooth',block:'center'})`);await sleep(900);}function cleanup(target,prefix){const resolved=realpathSync(target),temp=realpathSync(os.tmpdir());if(path.dirname(resolved)!==temp||!path.basename(resolved).startsWith(prefix))throw new Error('Небезопасный временный путь');rmSync(resolved,{recursive:true,force:true});}
async function main(){await waitJson(`http://127.0.0.1:${cdpPort}/json`);const pages=await waitJson(`http://127.0.0.1:${cdpPort}/json`);socket=new WebSocket(pages.find(item=>item.type==='page').webSocketDebuggerUrl);await new Promise(resolve=>socket.onopen=resolve);socket.onmessage=event=>{const data=JSON.parse(event.data);if(!data.id||!pending.has(data.id))return;const callback=pending.get(data.id);pending.delete(data.id);data.error?callback.reject(new Error(data.error.message)):callback.resolve(data.result)};await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Page.navigate',{url:`http://127.0.0.1:${port}/`});await sleep(1200);const cameraPromise=camera();
  await scene('Жизненный цикл задан явно','Пять состояний и только разрешённые стрелки загружаются из lifecycle.json. Модель не пишет состояние.','#timeline',4600);
  await click('#create');await waitText('state-name','Планирование');await scene('Новая задача начинается с планирования','Версия 1. Сейчас допустимо только submit_plan.','#state-name,#actions',3800);
  await click('#invalid');await waitText('status','заблокирован');await scene('Перепрыгнуть этап нельзя','Попытка approve_validation отклонена. Версия и артефакты не изменились.','#status,.event.rejected',4700);
  await scroll('#model-request');await click('#compare');await waitText('status','Сравнение завершено',1200);await scene('Один снимок — две модели','DeepSeek V4 Flash и Qwen3.8-27B видят одинаковое состояние. Их ответы не меняют версию.','#models,#status',6000);
  await scroll('#actions');await click('[data-action=submit_plan]');await waitText('state-name','Согласование');await scene('План представлен','Только после submit_plan задача попадает на отдельный этап согласования.','#state-name,#artifacts',3500);
  await click('[data-action=reject_plan]');await waitText('state-name','Планирование');await scene('Отклонение возвращает на доработку','Причина сохраняется отдельным артефактом, переход контролируемый.','#state-name,#artifacts',3800);
  await click('[data-action=submit_plan]');await click('[data-action=approve_plan]');await waitText('state-name','Реализация');await scene('Реализация открыта только после approve_plan','Утверждение плана записано в аудит.','#state-name,#actions',3600);
  await click('[data-action=submit_result]');await waitText('state-name','Валидация');await click('[data-action=fail_validation]');await waitText('state-name','Реализация');await scene('Неудачная проверка возвращает реализацию','Замечание validation_failure сохранено; завершения не произошло.','#state-name,#artifacts',4300);
  await click('[data-action=submit_result]');await waitText('state-name','Валидация');await click('#pause');await waitText('state-name','ПАУЗА');await click('#invalid');await waitText('status','сначала выполните resume');await scene('Во время паузы переходы заблокированы','Этап validation сохранён, попытка завершения попала в аудит как отказ.','#state-name,#status',4300);
  await cdp('Page.reload',{ignoreCache:true});await sleep(1200);await click('#load');await waitText('state-name','ПАУЗА');await scene('Новый процесс восстанавливает всё по task_id','Цель, validation, версия и все артефакты подняты из SQLite.','#state-name,#artifacts',4500);
  await click('#resume');await waitText('state-name','Валидация');await click('[data-action=approve_validation]');await waitText('state-name','Готово');await scene('Финал возможен только после валидации','approve_validation создаёт отчёт и переводит задачу в терминальное completed.','#state-name,#artifacts',4500);
  await click('#invalid');await waitText('status','Завершённую задачу нельзя изменить');await scroll('#history');await scene('Полный проверяемый аудит','Зелёным — разрешённые переходы, красным — попытки прыжка, действие на паузе и изменение финала.','#history',6000);
  recording=false;await cameraPromise;const encoded=spawnSync(process.env.FFMPEG_PATH||'ffmpeg',['-y','-framerate','8','-i',path.join(framesDir,'f%05d.png'),'-vf','fps=24,scale=trunc(iw/2)*2:trunc(ih/2)*2','-c:v','libx264','-pix_fmt','yuv420p','-crf','23',output],{stdio:'inherit'});if(encoded.status!==0)throw new Error('ffmpeg завершился с ошибкой');console.log(`Видео: ${output}`);
}
try{await main();}finally{recording=false;try{socket?.close()}catch{}try{chrome.kill()}catch{}try{server.kill()}catch{}cleanup(framesDir,'day15-frames-');cleanup(chromeDir,'day15-chrome-');}
