const $=id=>document.getElementById(id);
let current=null;
const taskId=()=> $('task-id').value.trim();
function status(text){$('status').textContent=text;}
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
function render(data){current=data.state;$('objective').value=current.objective;$('stage').textContent=current.stage;$('step').textContent=current.current_step;$('expected').textContent=current.expected_action||'—';$('paused').textContent=current.paused?'ПАУЗА':'активно';$('pause-reason').textContent=current.paused?`Причина: ${current.pause_reason}`:'';$('artifacts').textContent=JSON.stringify(current.artifacts,null,2);$('message').textContent=data.message;for(const node of document.querySelectorAll('[data-stage]')){node.className=node.dataset.stage===current.stage?'active':stageIndex(node.dataset.stage)<stageIndex(current.stage)?'past':'';}$('history').replaceChildren(...data.history.map(item=>{const node=document.createElement('div');node.className='event';const title=document.createElement('b');title.textContent=item.event;const route=document.createElement('small');route.textContent=`${item.from_stage||'—'} → ${item.to_stage}`;const detail=document.createElement('span');detail.textContent=item.details;node.append(title,route,detail);return node;}));status(data.message);}
function stageIndex(value){return ['planning','execution','validation','done'].indexOf(value);}
async function create(){render(await api('/api/task',{task_id:taskId(),objective:$('objective').value}));}
async function load(){render(await api(`/api/task?${new URLSearchParams({task_id:taskId()})}`));}
async function advance(){if(!current)throw new Error('Сначала загрузите задачу');render(await api('/api/action',{task_id:taskId(),action:current.expected_action,result:$('result').value}));$('result').value='';}
async function pause(){render(await api('/api/pause',{task_id:taskId(),reason:$('reason').value}));}
async function resume(){render(await api('/api/resume',{task_id:taskId()}));}
async function wrong(){await api('/api/action',{task_id:taskId(),action:'skip_everything',result:'Обход автомата'});}
async function compare(){if(!current)throw new Error('Сначала загрузите задачу');const button=$('compare');button.disabled=true;status('Две модели выполняют один и тот же шаг…');try{const data=await api('/api/compare',{task_id:taskId()});$('comparison-meta').textContent=`Одинаковый снимок: этап ${data.stage}, версия ${data.state_version}. Состояние автомата не изменено.`;$('model-results').replaceChildren(...data.results.map(item=>{const card=document.createElement('article');card.className='model-card';const title=document.createElement('h3');title.textContent=item.label;const meta=document.createElement('small');meta.textContent=`${item.provider} · ${item.model} · ${(item.elapsed_ms/1000).toFixed(1)} с`;const answer=document.createElement('p');answer.textContent=item.answer;const use=document.createElement('button');use.className='use-result';use.textContent='Использовать этот результат';use.addEventListener('click',()=>{$('result').value=item.answer;document.querySelectorAll('.model-card').forEach(node=>node.classList.remove('selected'));card.classList.add('selected');status(`Результат ${item.label} выбран, но переход ещё не выполнен.`);});card.append(title,meta,answer,use);return card;}));status('Сравнение готово: выберите результат перед переходом.');}finally{button.disabled=false;}}
for(const [id,fn] of [['create',create],['load',load],['advance',advance],['pause',pause],['resume',resume],['wrong',wrong],['compare',compare]])$(id).addEventListener('click',()=>fn().catch(error=>status(`Ошибка: ${error.message}`)));
